[package]
name = "domlet-macros"
description = "Compile-time .slint parser and Rust code generator for domlet (use the domlet crate)"
repository = "https://github.com/nursude355/Domlet"
version = "0.3.0"
edition = "2021"
license = "MIT"
rust-version = "1.81"
include = ["src/**", "Cargo.toml", "LICENSE-MIT"]

[lib]
proc-macro = true


[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "3.0.5", features = ["parsing", "proc-macro"] }
